

import Web3Provider from "@/components/Web3Provider";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

export const metadata = {
  title: "Hanber's Dapp",
  description: "Generated by Hanber",
  icons: {
    icon: "/hanber.png",
  },
};

export default async function RootLayout({ children }) {
  const locale = await getLocale()
  const message = await getMessages()
  
  return (
    <html lang={locale}>
      <head>
        {/* favicon replaced with hanber.png */}
        <link rel="icon" href="/hanber.png" />
      </head>
      <body className="dark">
        <NextIntlClientProvider>
          <Web3Provider>
            <NavBar />
            {children}
          </Web3Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
