

import Web3Provider from "@/components/Web3Provider";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

export const metadata = {
  title: "Hanber's Dapp",
  description: "Generated by Hanber",
  icons: {
    icon: "/hanber.png",
  },
};

const themeInitScript = `(() => {
  try {
    const raw = localStorage.getItem('theme-storage');
    let theme = 'dark';
    if (raw) {
      const parsed = JSON.parse(raw);
      theme = parsed?.state?.theme || parsed?.theme || theme;
    }
    const root = document.documentElement;
    if (theme === 'dark') root.classList.add('dark');
    else root.classList.remove('dark');
  } catch (e) {
    // no-op
  }
})();`;

export default async function RootLayout({ children }) {
  const locale = await getLocale()
  const message = await getMessages()
  
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        {/* favicon replaced with hanber.png */}
        <link rel="icon" href="/hanber.png" />
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body suppressHydrationWarning>
        <NextIntlClientProvider>
          <Web3Provider>
            <NavBar />
            {/* spacer equal to NavBar height to avoid content being covered by fixed NavBar */}
            <div className="h-16" aria-hidden="true" />
            {children}
          </Web3Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
